//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfZooApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int id { get; set; }
        public string name { get; set; }
        public int species_id { get; set; }
        public int enclosure_id { get; set; }
    }
}
