//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfZooApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedings
    {
        public int id { get; set; }
        public int animal_id { get; set; }
        public System.DateTime feeding_time { get; set; }
        public string notes { get; set; }
    }
}
